debug: true
site:
  domain: http://localhost:8080
  ip: 0.0.0.0
  port: 8080
  ssl:
    enable: false
    cert: /PATH/TO/CERT.PEM
    key: /PATH/TO/KEY.PEM
mysql:
  host: localhost
  port: 3306
  user: douyin
  pass: douyin
  name: douyin
salt: douyin
